In [1]:
from math import sqrt
import numpy as np
from numpy.typing import NDArray
from scipy.optimize import minimize, LinearConstraint, NonlinearConstraint

from qoptcraft.basis import get_photon_basis
from qoptcraft.state import PureState, MixedState, Fock
from qoptcraft.invariant import (
    can_transition,
    can_transition_basis,
    photon_invariant,
    photon_invariant_basis,
)

In [2]:
state = 1 / 2 * Fock(1, 0, 1, 0) + Fock(0, 1, 0, 1) * 1 / 2
print(state)

0.71 * (0, 1, 0, 1) + 
0.71 * (1, 0, 1, 0)


In [3]:
print(state.creation(1))

0.58 * (0, 2, 0, 1) + 
0.82 * (1, 1, 1, 0)


In [4]:
state.creation(3).coefs

array([1.        , 0.70710678])

In [5]:
from qoptcraft.state import Fock

Fock(1, 1, 1) + Fock(1, 0, 2) == 1 / 2 * Fock(1, 1, 1) + 1 / 2 * Fock(1, 0, 2) + 1 / 2 * Fock(
    0, 1, 2
)

False

In [6]:
[x for x in Fock(1, 1, 1)]

[1, 1, 1]

In [18]:
state = 1 / 2 * Fock(1, 1) + Fock(2, 0) * 1 / 2 - Fock(2, 0)
state

0.71 * (1, 1) + 
-0.71 * (2, 0)

In [16]:
state.amplitudes

array([0.31622777, 0.9486833 ])

In [19]:
fock_in = (0, 1, 2)
modes = len(fock_in)

for m in range(modes):
    for n in range(fock_in[m]):
        print(f"{m = }, {n = }")

m = 1, n = 0
m = 2, n = 0
m = 2, n = 1


In [69]:
state_out = Fock(*([0] * 2))

In [70]:
state_aux = state_out
state_out = 1 * state_out.creation(0)
state_out

1.00 * (1, 0)

In [71]:
state_out += -1 * state_aux.creation(1)
state_out

0.71 * (0, 1) + 
-0.71 * (1, 0)

In [72]:
Fock(1, 0) - Fock(0, 1)

0.71 * (0, 1) + 
-0.71 * (1, 0)

In [61]:
state_out.coefs

array([ 1., -1.])