# Evolution of photonic states through a linear interferometer

In [1]:
import numpy as np

from qoptcraft.evolution import photon_unitary
from qoptcraft.optical_elements import beam_splitter
from qoptcraft.operators import haar_random_unitary


np.set_printoptions(precision=2)

We can begin by quantizing a simple beam splitter:

In [2]:
modes = 4
photons = 3

In [3]:
bs = beam_splitter(angle=2, shift=0, dim=modes, mode_1=1, mode_2=2)
photonic_bs = photon_unitary_permanent(bs, photons, method="ryser")

Now we can try with a random unitary:

In [4]:
random_s = haar_random_unitary(modes)
unitary = photon_unitary(random_s, photons)
unitary_from_H = photon_unitary_hamiltonian(random_s, photons)
unitary_glynn = photon_unitary_permanent(random_s, photons, method="glynn")
unitary_ryser = photon_unitary_permanent(random_s, photons, method="ryser")

We can check that all of them give the same matrix, albeit a global phase.

In [5]:
from itertools import combinations
from numpy.testing import assert_allclose

for U_1, U_2 in combinations([unitary, unitary_from_H, unitary_glynn, unitary_ryser], 2):
    try:
        assert_allclose(U_1, U_2)
    except AssertionError:
        assert_allclose(U_1, -U_2)

If we are only interested in the output of a Fock state, we can use another function

In [6]:
from qoptcraft.evolution import fock_evolution, fock_evolution_permanent

In [7]:
in_state = (0,1,0,1)
out_state = fock_evolution_permanent(bs, in_state)
out_state

array([ 0.  +0.j,  0.91+0.j,  0.  +0.j, -0.42+0.j,  0.  +0.j,  0.  +0.j,
        0.  +0.j,  0.  +0.j,  0.  +0.j,  0.  +0.j])

In [8]:
np.abs(out_state @ out_state.conj().T)**2

0.9999999401495314

In [9]:
photonic_bs

array([[-1.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,
         0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,
         0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,
         0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,
         0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j],
       [ 0.00e+00+0.j,  4.16e-01-0.j,  0.00e+00+0.j,  0.00e+00+0.j,
        -9.09e-01+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,
         0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,
         0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,
         0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j],
       [ 0.00e+00+0.j,  0.00e+00+0.j, -1.73e-01+0.j, -1.20e-17+0.j,
         0.00e+00+0.j,  5.35e-01-0.j,  5.55e-17-0.j, -8.27e-01+0.j,
        -5.55e-17+0.j, -3.20e-17+0.j,  0.00e+00+0.j,  0.00e+00+0.j,
         0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,
         0.00e+00+0.j,  0.00e+00+0.j,  0.00e+0

In [1]:
from qoptcraft.optical_elements import beam_splitter
import numpy as np

S = beam_splitter(np.pi/4, 0, 2, 0, 1)

ModuleNotFoundError: No module named 'qoptcraft.evolution.hamiltonian_evolution'

In [15]:
S

array([[ 0.71+0.j, -0.71+0.j],
       [ 0.71+0.j,  0.71+0.j]], dtype=complex64)

In [16]:
from qoptcraft.evolution import photon_unitary

photon_unitary(S, 2)

array([[ 0.5 +0.j,  0.71+0.j,  0.5 +0.j],
       [-0.71+0.j,  0.  +0.j,  0.71+0.j],
       [ 0.5 +0.j, -0.71+0.j,  0.5 +0.j]], dtype=complex64)