In [1]:
import numpy as np

from qoptcraft.optical_elements import beam_splitter
from qoptcraft.evolution import photon_unitary
from qoptcraft.state import Fock

from qoptcraft.invariant import projection_density, spectral_invariant

np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3g" % x))

In [2]:
from qoptcraft.basis import complete_photon_basis, photon_basis

In [7]:
first_fock = [[2,1,0], [1,1,1]]

In [8]:
complete_photon_basis(first_fock)

[(3, 0, 0),
 (2, 0, 1),
 (1, 2, 0),
 (1, 0, 2),
 (0, 3, 0),
 (0, 2, 1),
 (0, 1, 2),
 (0, 0, 3)]

In [9]:
photon_basis(3,3)

[(3, 0, 0),
 (2, 1, 0),
 (2, 0, 1),
 (1, 2, 0),
 (1, 1, 1),
 (1, 0, 2),
 (0, 3, 0),
 (0, 2, 1),
 (0, 1, 2),
 (0, 0, 3)]

In [5]:
tuple([1,2,1])

(1, 2, 1)

In [8]:
spectral_invariant(Fock(3,3))

array([18, 18, 18, 18, 18, 18, 18])

In [9]:
spectral_invariant(Fock(6,0) + Fock(0,6))

array([18, 18, 18, 18, 18, 18, 18])

In [37]:
def heralded_fock(a):
    return a[0] * Fock(2,0) + a[1] * Fock(0,2) + a[2] * Fock(1,1)

In [38]:
def cost(a):
    state = heralded_fock(a)
    invariant = spectral_invariant(state)
    target_invariant = np.array([2,2,2])
    c = np.inner(target_invariant - invariant, target_invariant - invariant)
    # print(f"cost = {c}")
    return c

In [54]:
import scipy as sp
BS = beam_splitter(0.3,0,2,0,1)
S = sp.linalg.block_diag(BS,BS)

photon_unitary(S,3)

Photon basis saved in /Users/KaerMorhen/Documents/Code projects/qoptcraft/examples/save_basis/m=4 n=3/photon.pkl.


array([[-8.71904919e-01+0.j,  4.67154541e-01-0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j, -1.44507835e-01+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  2.58084301e-02-0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
       [-4.67154541e-01+0.j, -7.05041644e-01+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  5.13615170e-01-0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j, -1.44507835e-01+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
       [ 0.00000000e+00+0.j,  0.00000000e+00+0.j, -8.71904919e-01+0.j,  2.69711800e-01-0.j,  0.00000000e+00+0.j,  3.81430086e-01-0.j, -1.17990

In [39]:
from scipy.optimize import minimize

x0 = np.array([0.2,0.2,0.2])
minimize(cost, x0, method="COBYLA")

 message: Optimization terminated successfully.
 success: True
  status: 1
     fun: 9.469774192596131e-08
       x: [ 4.488e-01 -4.489e-01  1.733e+00]
    nfev: 46
   maxcv: 0.0

In [40]:
state = heralded_fock([4.488e-01, -4.489e-01,  1.733e+00])
state

0.24 * (2, 0) + 
0.94 * (1, 1) + 
-0.24 * (0, 2)

In [36]:
spectral_invariant(state)

array([1.99984678, 2.00000006, 2.00015334])

In [12]:
heralded_fock([0.3,4,-2])

0.07 * (2, 0) + 
-0.45 * (1, 1) + 
0.89 * (0, 2)

In [30]:
from qoptcraft.invariant import projection_density, spectral_invariant

spectral_invariant(heralded_fock(0.5,0))

TypeError: heralded_fock() takes 1 positional argument but 2 were given

In [14]:
spectral_invariant(Fock(1,1))

array([2., 2., 2.])

In [2]:
from qoptcraft.invariant import projection_coefs

state = Fock(1,2) + 0.5 * Fock(3,0)
state_projection_coefs = projection_coefs(state)
state_projection_coefs

array([1.39999992+0.j, 1.5999999 +0.j, 0.        +0.j, 0.        +0.j])

In [3]:
from qoptcraft.invariant import projection_density
state_projetion = projection_density(state)
state_projetion

matrix([[0.+4.19999975j, 0.+0.j        , 0.+0.j        , 0.+0.j        ],
        [0.+0.j        , 0.+4.39999974j, 0.+0.j        , 0.+0.j        ],
        [0.+0.j        , 0.+0.j        , 0.+4.59999973j, 0.+0.j        ],
        [0.+0.j        , 0.+0.j        , 0.+0.j        , 0.+4.79999971j]])

In [4]:
from qoptcraft.basis import image_matrix_from_coefs

image_matrix_from_coefs(state_projection_coefs, state.modes, state.photons)

matrix([[0.+4.19999975j, 0.+0.j        , 0.+0.j        , 0.+0.j        ],
        [0.+0.j        , 0.+4.39999974j, 0.+0.j        , 0.+0.j        ],
        [0.+0.j        , 0.+0.j        , 0.+4.59999973j, 0.+0.j        ],
        [0.+0.j        , 0.+0.j        , 0.+0.j        , 0.+4.79999971j]])

In [ ]:
from qoptcraft.basis import hermitian_matrix_from_coefs

hamiltonian = hermitian_matrix_from_coefs(state_projection_coefs, 2)
hamiltonian

TypeError: hermitian_matrix_from_coefs() missing 1 required positional argument: 'dim'

In [6]:
from qoptcraft.basis import hermitian_matrix_from_coefs

hermitian_matrix_from_coefs(projection_coefs(Fock(1,1)), 2)


array([[0.+1.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [6]:
from qoptcraft.evolution import photon_hamiltonian

photon_hamiltonian(hamiltonian, 3).round(5)

array([[0.+4.2j, 0.+0.j , 0.+0.j , 0.+0.j ],
       [0.+0.j , 0.+4.4j, 0.+0.j , 0.+0.j ],
       [0.+0.j , 0.+0.j , 0.+4.6j, 0.+0.j ],
       [0.+0.j , 0.+0.j , 0.+0.j , 0.+4.8j]])

In [9]:
from qoptcraft.optical_elements import beam_splitter
from qoptcraft.operators import haar_random_unitary

# S = beam_splitter(np.pi/4,0,2,0,1)
modes = 3
photons = 2
S = haar_random_unitary(modes)
U = photon_unitary(S, photons)

In [10]:
from qoptcraft.basis import unitary_algebra_basis

def matrix_C(S):
    modes = S.shape[0]
    basis = unitary_algebra_basis(modes)
    C = np.zeros((modes**2, modes**2), dtype=np.complex128)
    for i in range(modes**2):
        for j in range(modes**2):
            C[i,j] = hs_inner_product(S @ basis[i] @ S.conj().T, basis[j])
    return C

In [11]:
from qoptcraft.basis.algebra import sym_matrix, antisym_matrix

def scattering_from_coefs(coef_matrix):
    """Retrieve the linear optical scattering matrix from a unitary using Theorem 2
    of PRA 100, 022301 (2019).

    Args:
        unitary (NDArray): unitary matrix.
        modes (int): number of modes in the optical system.
        photons (int): number of photons.

    Returns:
        NDArray: optical scattering matrix that maps to the given unitary.
    """

    basis = unitary_algebra_basis(modes)

    basis_array = np.array(basis)

    def adjoint(basis_matrix):
        for i in range(len(basis)):
            if (basis_matrix == basis[i]).all():
                index = i
                break
        return np.einsum("k,kij->ij", coef_matrix[index, :], basis_array)

    def get_nonzero_element():
        for j in range(modes):
            basis_matrix = sym_matrix(j, j, modes)
            for l in range(modes):
                exp_val = adjoint(basis_matrix)[l,l]
                if not np.isclose(exp_val, 0, rtol=1e-5, atol=1e-8):
                    j0, l0 = j, l
                    coef = np.sqrt(-1j * exp_val)
                    return j0, l0, coef
        raise ValueError("Nonzero element not found.")

    j0, l0, coef = get_nonzero_element()
    scattering = np.zeros((modes, modes), dtype=np.complex128)
    for l in range(modes):
        for j in range(modes):
            sym_term = adjoint(sym_matrix(j, j0, modes))[l,l0]
            if j != j0:
                antisym_term = adjoint(antisym_matrix(j, j0, modes))[l, l0]
                # ! The factor np.sqrt(2) / 2 is to transform the basis into the one in the paper
                scattering[l, j] = (antisym_term - 1j * sym_term) / coef * np.sqrt(2) / 2
            else:
                scattering[l, j] = - 1j * sym_term / coef
    return scattering

In [12]:
def hausholder_reflection(vector_1, vector_2):
    u = vector_1 - vector_2
    u = u / np.linalg.norm(u)
    return np.eye(u.size) - 2 * np.outer(u, u.conj())

In [13]:
from qoptcraft.operators import haar_random_unitary
from qoptcraft.state import Fock

modes = 3
photons = 2
S = haar_random_unitary(modes)
U = photon_unitary(S, photons)

in_state = Fock(1,1,0) + 0.5 * Fock(2,0,0)
out_state = in_state.evolution(U)
in_state_coefs = projection_coefs(in_state)
out_state_coefs = projection_coefs(out_state)

# C = matrix_C(S)
C = hausholder_reflection(in_state_coefs, out_state_coefs)

for n in range(modes**2):
    sum = 0
    for i in range(modes**2):
        sum += in_state_coefs[i] * C[i, n]
    np.testing.assert_almost_equal(sum, out_state_coefs[n],decimal=6)

In [17]:
from qoptcraft.math import commutator

commutator(in_state.density_matrix, out_state.density_matrix)

array([[ 0.        -0.06536325j,  0.03093206-0.04902244j,
        -0.04147333+0.13145709j, -0.09775133+0.01833699j,
        -0.04469376-0.03372515j, -0.01991763-0.07654694j],
       [-0.03093206-0.04902244j,  0.        +0.06536325j,
        -0.08294667+0.26291418j, -0.19550267+0.03667398j,
        -0.08938753-0.06745029j, -0.03983526-0.15309387j],
       [ 0.04147333+0.13145709j,  0.08294667+0.26291418j,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.09775133+0.01833699j,  0.19550267+0.03667398j,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.04469376-0.03372514j,  0.08938753-0.06745028j,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.01991763-0.07654694j,  0.03983526-0.15309387j,
         0.        +0.j        ,  0.        +0.j        ,
         

In [14]:
S_rebuilt = scattering_from_coefs(hausholder_reflection(in_state_coefs, out_state_coefs))

In [15]:
from qoptcraft.basis import hermitian_matrix_from_coefs

in_matrix = hermitian_matrix_from_coefs(in_state_coefs, 3)

(S_rebuilt @ in_matrix @ np.linalg.inv(S_rebuilt)).round(5)

array([[-0.3639 +1.84708j,  0.1095 +2.01887j,  0.08846+1.09486j],
       [ 0.14782+0.40781j,  0.3639 +0.9043j ,  0.17796+0.38988j],
       [ 0.33042-0.99852j, -0.00949-1.5157j , -0.     -0.75138j]])

In [ ]:
from qoptcraft.basis import hermitian_matrix_from_coefs

in_matrix = hermitian_matrix_from_coefs(in_state_coefs, 3)

(S @ in_matrix @ S.conj().T).round(5)

array([[-0.     +1.28517j, -0.47647+0.22957j, -0.10868-0.04555j],
       [ 0.47647+0.22957j, -0.     +0.61675j, -0.21066-0.0344j ],
       [ 0.10868-0.04555j,  0.21066-0.0344j ,  0.     +0.09808j]])

In [ ]:
out_matrix = hermitian_matrix_from_coefs(out_state_coefs, 3)
out_matrix.round(5)

array([[-0.     +1.28517j, -0.47647+0.22957j, -0.10868-0.04555j],
       [ 0.47647+0.22957j, -0.     +0.61675j, -0.21066-0.0344j ],
       [ 0.10868-0.04555j,  0.21066-0.0344j ,  0.     +0.09808j]])

In [ ]:
C @ in_state_coefs

array([ 1.2851687 -1.19486831e-09j,  0.61674871+9.13615476e-09j,
        0.32466044-7.34385230e-09j,  0.67382778-1.09463961e-08j,
        0.09808266-1.98645560e-09j, -0.06441291-1.38547578e-08j,
        0.1536916 -2.49673465e-09j, -0.04865424-7.52672062e-10j,
        0.29791989-4.83973691e-09j])

In [ ]:
out_state_coefs

array([ 1.28516876+1.88706606e-10j,  0.61674859+6.15922491e-09j,
        0.32466014-1.50657973e-08j,  0.67382821+6.93889390e-18j,
        0.09808272-3.93093780e-10j, -0.06441295-1.49011612e-08j,
        0.1536917 +0.00000000e+00j, -0.04865427-1.54306576e-09j,
        0.29792008+0.00000000e+00j])

In [ ]:
S * np.abs(S[0,0]) / S[0,0]

array([[ 0.81833326-0.j        , -0.0579191 +0.30102655j,
         0.48600339+0.01264025j],
       [ 0.23840485-0.15064009j, -0.62965368+0.28955436j,
        -0.65272217-0.11882329j],
       [ 0.36175647+0.34631434j,  0.65230479+0.01487849j,
        -0.53562963-0.19125016j]])

In [ ]:
S @ S.T.conj()

array([[ 1.00000000e+00+2.62788462e-17j,  5.57495597e-18-7.12284114e-17j,
         8.66745244e-17-2.80812974e-16j],
       [ 5.57495597e-18+7.57169719e-17j,  1.00000000e+00-9.42436072e-18j,
        -2.40882842e-16+1.41950187e-16j],
       [ 8.66745244e-17+2.89529009e-16j, -2.40882842e-16-1.25181106e-16j,
         1.00000000e+00-8.84105723e-18j]])

In [ ]:
# S_rebuilt = scattering_from_coefs(matrix_C(S))
S_rebuilt = scattering_from_coefs(hausholder_reflection(in_state_coefs, out_state_coefs))
S_rebuilt @ S_rebuilt.conj().T

array([[ 0.96070197-2.84311488e-19j, -0.21082828-3.35247223e-02j,
         0.25622983-4.39501062e-02j],
       [-0.21082828+3.35247223e-02j,  0.78087491+1.23966771e-18j,
         0.37076503-1.25989214e-01j],
       [ 0.25622983+4.39501062e-02j,  0.37076503+1.25989214e-01j,
         0.62555514-1.23966771e-18j]])

In [ ]:
S_rebuilt @ S_rebuilt.conj().T

array([[ 0.96070197-2.84311488e-19j, -0.21082828-3.35247223e-02j,
         0.25622983-4.39501062e-02j],
       [-0.21082828+3.35247223e-02j,  0.78087491+1.23966771e-18j,
         0.37076503-1.25989214e-01j],
       [ 0.25622983+4.39501062e-02j,  0.37076503+1.25989214e-01j,
         0.62555514-1.23966771e-18j]])

In [ ]:
U_rebuilt = photon_unitary(S_rebuilt, photons)
out_state_rebuilt = in_state.evolution(U)
out_state_rebuilt

0.35-0.19j * (2, 0, 0) + 
0.15+0.34j * (1, 1, 0) + 
0.36-0.50j * (1, 0, 1) + 
0.15+0.15j * (0, 2, 0) + 
-0.18+0.04j * (0, 1, 1) + 
0.45-0.23j * (0, 0, 2)

In [ ]:
out_state

0.35-0.19j * (2, 0, 0) + 
0.15+0.34j * (1, 1, 0) + 
0.36-0.50j * (1, 0, 1) + 
0.15+0.15j * (0, 2, 0) + 
-0.18+0.04j * (0, 1, 1) + 
0.45-0.23j * (0, 0, 2)

In [ ]:
from qoptcraft.basis import hilbert_dim

def projection_coefs_matrix(hermitian_matrix, modes, photons, orthonormal = False):
    if orthonormal:
        basis_image = image_algebra_basis_orthonormal(modes, photons)
    else:
        basis_image = image_algebra_basis(modes, photons)
    coefs = []
    matrix = 1j * hermitian_matrix
    for basis_matrix in basis_image:
        coefs.append(hs_inner_product(basis_matrix, matrix))
    return np.array(coefs)

def inverse_algebra_hm(tangent_state, modes, photons, orthonormal = False):

    coefs = projection_coefs_matrix(tangent_state, modes, photons, orthonormal)
    inverse_tangent_state = np.zeros((modes, modes), dtype=np.complex128)
    original_tangent_matrix = np.zeros_like(tangent_state, dtype=np.complex128)

    for image_matrix, unitary_matrix, coef in zip(image_algebra_basis(modes, photons), unitary_algebra_basis(modes), coefs):
        inverse_tangent_state += coef * unitary_matrix
        original_tangent_matrix += coef * image_matrix
    return inverse_tangent_state, original_tangent_matrix

In [ ]:
from qoptcraft.invariant import projection_density
import scipy as sp

orthonormal = True

in_state_tangent = projection_density(in_state, orthonormal=orthonormal)
out_state_tangent = projection_density(out_state, orthonormal=orthonormal)


In [ ]:
in_state_tangent

matrix([[0.+0.37999998j, 0.+0.15999999j, 0.+0.j        , 0.+0.j        ,
         0.+0.j        , 0.+0.j        ],
        [0.+0.15999999j, 0.+0.29999998j, 0.+0.j        , 0.+0.15999999j,
         0.+0.j        , 0.+0.j        ],
        [0.+0.j        , 0.+0.j        , 0.+0.13999999j, 0.+0.j        ,
         0.+0.11313708j, 0.+0.j        ],
        [0.+0.j        , 0.+0.15999999j, 0.+0.j        , 0.+0.21999999j,
         0.+0.j        , 0.+0.j        ],
        [0.+0.j        , 0.+0.j        , 0.+0.11313708j, 0.+0.j        ,
         0.+0.06j      , 0.+0.j        ],
        [0.+0.j        , 0.+0.j        , 0.+0.j        , 0.+0.j        ,
         0.+0.j        , 0.-0.09999999j]])

In [ ]:
from qoptcraft.evolution import photon_hamiltonian

hamiltonian, reconstructed_tangent = inverse_algebra_hm(in_state_tangent, modes, photons, orthonormal)
print(f"{hamiltonian = }")
print(f"{reconstructed_tangent.round(5) = }")

hamiltonian = array([[-0.48989792+0.j, -0.2529822 +0.j,  0.        +0.j],
       [-0.2529822 +0.j, -0.24842359+0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.11952285+0.j]])
reconstructed_tangent.round(5) = matrix([[-0.9798 +0.j, -0.35777+0.j,  0.     +0.j,  0.     +0.j,
          0.     +0.j,  0.     +0.j],
        [-0.35777+0.j, -0.73832+0.j,  0.     +0.j, -0.35777+0.j,
          0.     +0.j,  0.     +0.j],
        [ 0.     +0.j,  0.     +0.j, -0.37038+0.j,  0.     +0.j,
         -0.25298+0.j,  0.     +0.j],
        [ 0.     +0.j, -0.35777+0.j,  0.     +0.j, -0.49685+0.j,
          0.     +0.j,  0.     +0.j],
        [ 0.     +0.j,  0.     +0.j, -0.25298+0.j,  0.     +0.j,
         -0.1289 +0.j,  0.     +0.j],
        [ 0.     +0.j,  0.     +0.j,  0.     +0.j,  0.     +0.j,
          0.     +0.j,  0.23905+0.j]])


In [ ]:
photon_hamiltonian(hamiltonian, photons).round(5)

array([[-0.9798 +0.j, -0.35777+0.j,  0.     +0.j,  0.     +0.j,
         0.     +0.j,  0.     +0.j],
       [-0.35777+0.j, -0.73832+0.j,  0.     +0.j, -0.35777+0.j,
         0.     +0.j,  0.     +0.j],
       [ 0.     +0.j,  0.     +0.j, -0.37038+0.j,  0.     +0.j,
        -0.25298+0.j,  0.     +0.j],
       [ 0.     +0.j, -0.35777+0.j,  0.     +0.j, -0.49685+0.j,
         0.     +0.j,  0.     +0.j],
       [ 0.     +0.j,  0.     +0.j, -0.25298+0.j,  0.     +0.j,
        -0.1289 +0.j,  0.     +0.j],
       [ 0.     +0.j,  0.     +0.j,  0.     +0.j,  0.     +0.j,
         0.     +0.j,  0.23905+0.j]])

In [ ]:
in_state_tangent.round(5)

matrix([[0.+2.4j    , 0.+0.8j    , 0.+0.j     , 0.+0.j     , 0.+0.j     ,
         0.+0.j     ],
        [0.+0.8j    , 0.+2.j     , 0.+0.j     , 0.+0.8j    , 0.+0.j     ,
         0.+0.j     ],
        [0.+0.j     , 0.+0.j     , 0.+1.2j    , 0.+0.j     , 0.+0.56569j,
         0.+0.j     ],
        [0.+0.j     , 0.+0.8j    , 0.+0.j     , 0.+1.6j    , 0.+0.j     ,
         0.+0.j     ],
        [0.+0.j     , 0.+0.j     , 0.+0.56569j, 0.+0.j     , 0.+0.8j    ,
         0.+0.j     ],
        [0.+0.j     , 0.+0.j     , 0.+0.j     , 0.+0.j     , 0.+0.j     ,
         0.+0.j     ]])

In [ ]:
in_state_coefs.real

array([1.19999993, 0.79999995, 0.79999995, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [ ]:
out_state_coefs.real

array([ 0.38999393,  1.43735607, -0.20162702,  0.13328514,  0.17265005,
        0.24856562,  0.09166545, -0.45446801, -0.37007744])

In [ ]:
np.arctan((out_state_coefs[0] - in_state_coefs[1]) / in_state_coefs[0])

(-0.32923622223401566+1.0335488277069376e-09j)

In [ ]:
in_state = Fock(1,1)
in_state_coefs = projection_coefs(in_state)
out_state = Fock(2,0) + Fock(0,2)
out_state_coefs = projection_coefs(out_state)

modes = 2

for n in range(modes**2):
    sum = 0
    for i in range(modes**2):
        sum += in_state_coefs[i] * C[i, n]
    np.testing.assert_almost_equal(sum, out_state_coefs[n])

In [ ]:
from numpy.typing import NDArray
from qoptcraft.basis import image_algebra_basis
from qoptcraft.operators import adjoint_evol
import sympy


class InconsistentEquations(ValueError):
    def __init__(self, rank, expected_rank: float) -> None:
        message = f"The system has rank {rank} but should be {expected_rank}."
        super().__init__(message)


def equation_matrix_state(state):
    coefs = projection_coefs(state)
    return equation_matrix(coefs, state.modes, state.photons)


def equation_matrix(coefs, modes: int, photons: int) -> NDArray:
    """Matrix of the system of equations.

    Args:
        modes (int): number of modes in the optical system.
        basis_image (BasisAlgebra): basis of the image algebra.

    Returns:
        NDArray: matrix of the system of equations.
    """
    basis_image = image_algebra_basis(modes, photons)
    dim = basis_image[0].shape[0]
    eq_matrix = np.empty((dim**2, modes**2), dtype=np.complex128)
    for k in range(dim):
        for l in range(dim):
            for i in range(modes):
                for j in range(modes):
                    eq_matrix[dim * k + l, i * modes + j] = basis_image[i][k, l] * coefs[j]
    return eq_matrix

def check_consistency(equation_matrix, indep_term):
    eq_matrix_sym = sympy.Matrix(equation_matrix).T
    reduced_matrix, pivots = eq_matrix_sym.rref()  # reduced row echelon form
    if len(pivots) > equation_matrix.shape[1]:
        raise InconsistentEquations(len(pivots), equation_matrix.shape[1])
    return pivots

In [ ]:
def check_consistency(equation_matrix, indep_term):
    augmented_matrix = np.c_[equation_matrix, indep_term.reshape(-1,1)]
    return np.linalg.matrix_rank(equation_matrix) == np.linalg.matrix_rank(augmented_matrix)

In [ ]:
from qoptcraft.invariant import projection_density

in_state = Fock(1,1)
out_state = Fock(2,0) + Fock(0,2)

eq_matrix = equation_matrix_state(in_state)
indep_term = np.array(projection_density(out_state, orthonormal=True)).flatten().reshape(-1)
check_consistency(eq_matrix, indep_term)

True

In [ ]:
tangent_in = projection_density(in_state, subspace='complement', orthonormal=True)
tangent_out = projection_density(out_state, subspace='complement', orthonormal=True)

In [ ]:
tangent_in

matrix([[0.-0.33333333j, 0.+0.j        , 0.+0.j        ],
        [0.+0.j        , 0.+0.66666667j, 0.+0.j        ],
        [0.+0.j        , 0.+0.j        , 0.-0.33333333j]])

In [ ]:
tangent_out

matrix([[0.+0.16666666j, 0.+0.j        , 0.+0.49999997j],
        [0.+0.j        , 0.-0.33333331j, 0.+0.j        ],
        [0.+0.49999997j, 0.+0.j        , 0.+0.16666666j]])

In [ ]:
eq_matrix

array([[0.+0.89442719j, 0.+0.73029674j, 0.+0.j        , 0.+0.j        ],
       [0.+0.j        , 0.+0.j        , 0.+0.j        , 0.+0.j        ],
       [0.+0.j        , 0.+0.j        , 0.+0.j        , 0.+0.j        ],
       [0.+0.j        , 0.+0.j        , 0.+0.j        , 0.+0.j        ],
       [0.+0.4472136j , 0.+0.36514837j, 0.+0.4472136j , 0.+0.36514837j],
       [0.+0.j        , 0.+0.j        , 0.+0.j        , 0.+0.j        ],
       [0.+0.j        , 0.+0.j        , 0.+0.j        , 0.+0.j        ],
       [0.+0.j        , 0.+0.j        , 0.+0.j        , 0.+0.j        ],
       [0.+0.j        , 0.+0.j        , 0.+0.89442719j, 0.+0.73029674j]])

In [ ]:
indep_term

array([0.+0.33333331j, 0.+0.j        , 0.+0.j        , 0.+0.j        ,
       0.+0.33333331j, 0.+0.j        , 0.+0.j        , 0.+0.j        ,
       0.+0.33333331j])

In [ ]:
def solution_coefs(eq_matrix, indep_term) -> NDArray:
    eq_matrix_sym = sympy.Matrix(eq_matrix)
    reduced_matrix, pivots = eq_matrix_sym.rref()  # reduced row echelon form
    print(eq_matrix[pivots, :])
    print(indep_term[pivots, ...])
    return np.linalg.solve(eq_matrix[pivots, :], indep_term[pivots, ...])

In [ ]:
solution_coefs(eq_matrix, indep_term)

[[0.+0.89442719j 0.+0.73029674j 0.+0.j         0.+0.j        ]
 [0.+0.j         0.+0.j         0.+0.j         0.+0.j        ]]
[0.+0.33333331j 0.+0.j        ]


LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
indep_term[pivots, ...]

In [ ]:
np.linalg.lstsq(eq_matrix, indep_term, rcond=None)

(array([0.22360678-4.67711900e-34j, 0.18257417+2.36700330e-18j,
        0.22360678-9.85191136e-18j, 0.18257417+2.31061409e-19j]),
 array([], dtype=float64),
 2,
 array([1.41421356e+00, 1.15470054e+00, 1.00226983e-16, 1.19774135e-17]))

In [ ]:
solution = np.real(np.array([0.22360678-4.67711900e-34j, 0.18257417+2.36700330e-18j,
        0.22360678-9.85191136e-18j, 0.18257417+2.31061409e-19j]))
solution

array([0.22360678, 0.18257417, 0.22360678, 0.18257417])

In [ ]:
def projection_from_coefs(state, coefs):
    basis_image = image_algebra_basis_orthonormal(state.modes, state.photons)
    projection = np.zeros_like(basis_image[0])
    for i, basis_matrix in enumerate(basis_image):
        projection += coefs[i] * basis_matrix
    print(projection.toarray())
    return projection

In [ ]:
from qoptcraft.state import Fock

coefs = projection_coefs(Fock(1,1))
projection_from_coefs(Fock(1,1), coefs)

[[0.+0.33333333j 0.+0.j         0.+0.j        ]
 [0.+0.j         0.+0.33333333j 0.+0.j        ]
 [0.+0.j         0.+0.j         0.+0.33333333j]]


<3x3 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

In [ ]:
def solution_coefs(state_in, state_out) -> NDArray:
    """Coefficients that solve the system of equations that the unitary must satisfy.

    Returns:
        NDArray: matrix with the coefficients that solve the system.
    """
    assert state_in.modes == state_out.modes
    assert state_in.photons == state_out.photons

    modes = state_in.modes
    photons = state_in.photons
    basis_image = image_algebra_basis(modes, photons)

    sol_coefs = []
    eq_matrix = equation_matrix(coefs, modes, basis_image)
    eq_matrix_sym = sympy.Matrix(eq_matrix).T
    reduced_matrix, pivots = eq_matrix_sym.rref()  # reduced row echelon form
    if len(pivots) > modes**2:
        raise InconsistentEquations(len(pivots), modes**2)
    else:
        # If linear independent equations
        indep_term =  # ! coefs de 
        solution = np.linalg.solve(eq_matrix[pivots, :], indep_term[pivots, ...])
        sol_coefs.append(solution)
    return np.vstack(sol_coefs, dtype=np.complex128)  # array with sol_coefs elements as rows

SyntaxError: invalid syntax (1341024826.py, line 22)

In [ ]:
from qoptcraft.state import Fock
from qoptcraft.invariant import photon_invariant, spectral_invariant

bell_dual_rail = Fock(1,0,1,0) + Fock(0,1,0,1)
print("Bell invariant = ", photon_invariant(bell_dual_rail))
print("Fock invariant = ", photon_invariant(Fock(1,1,0,0)))

Bell invariant =  0.0999999880790714
Fock invariant =  0.2666666666666666


In [ ]:
state = Fock(2,1) + Fock(0,3)
spectral_invariant(state)

array([2.99999982, 3.99999976, 4.9999997 , 5.99999964])

In [ ]:
S = beam_splitter(angle=np.pi/4, shift=0, dim=2, mode_1=0, mode_2=1)
U = photon_unitary(S, photons=2, method='permanent glynn')

fock_density = Fock(1,1).density_matrix
fock_density_1 = np.diag([-1,0,0])
fock_density_2 = fock_density - fock_density_1


In [ ]:
fock_density_1_evol = U @ fock_density_1 @ U.conj().T
fock_density_2_evol = U @ fock_density_2 @ U.conj().T

In [ ]:
photon_invariant_basis(fock_density_2_evol,2,2)

NameError: name 'photon_invariant_basis' is not defined

In [ ]:
photon_invariant_basis(fock_density_2_evol,2,2)

NameError: name 'photon_invariant_basis' is not defined

In [ ]:
Bell = PureState([[1,0,1,0,1,1],[0,1,0,1,1,1]],[1/np.sqrt(2), 1/np.sqrt(2)])
spectral_invariant(Bell, subspace='complement', orthonormal=True)

NameError: name 'PureState' is not defined

In [ ]:
scalar_invariant_from_matrix(Fock(4,0).density_matrix, 2, 4, 2)

(16+0j)

In [ ]:
from qoptcraft import haar_random_unitary, photon_unitary, scattering_from_unitary

modes = 2
photons = 2
S = haar_random_unitary(modes)
S * np.abs(S[0,0]) / S[0,0]

array([[ 0.47308167+0.j        , -0.83334361+0.28588838j],
       [ 0.09860751+0.87548289j,  0.2026334 +0.42748797j]])

In [ ]:
U = photon_unitary(S, photons)
S_rebuilt = scattering_from_unitary(U, modes, photons)
S_rebuilt * np.abs(S_rebuilt[0,0]) / S_rebuilt[0,0]

array([[ 0.47308167+0.j        , -0.83334361+0.28588838j],
       [ 0.09860751+0.87548289j,  0.2026334 +0.42748797j]])

In [ ]:
S_rebuilt.conj().T @ S_rebuilt

array([[ 1.00000000e+00-3.89324133e-18j, -1.56852330e-16-4.88741333e-16j,
         6.67418097e-17-8.47132576e-17j],
       [-1.56852330e-16+5.00300016e-16j,  1.00000000e+00-2.66158367e-18j,
        -3.80951538e-17+9.03737383e-18j],
       [ 6.67418097e-17+7.59265331e-17j, -3.80951538e-17-9.04652781e-18j,
         1.00000000e+00+9.28473281e-18j]])

In [ ]:
S.conj().T @ S

array([[1.00000000e+00-3.87367221e-18j, 4.96176327e-17+9.61227783e-17j],
       [4.96176327e-17-8.34514785e-17j, 1.00000000e+00-2.32023306e-18j]])

In [ ]:
S / S[0,0]

array([[ 1.        -0.j        , -0.57070504+0.27842186j,
         0.66022517-1.52130725j],
       [ 0.0492536 +0.88879111j,  1.32853168-0.9259798j ,
        -0.34726658-0.78618786j],
       [ 0.71479325-1.36021728j,  0.94823192-0.47821985j,
         0.73775143+0.34678578j]])

In [ ]:
S_rebuilt

array([[ 0.49067406-4.10162368e-18j, -0.19801123+9.66009591e-02j,
         0.32395537-7.46466009e-01j],
       [ 0.02416746+4.36106743e-01j,  0.46094597-3.21276985e-01j,
        -0.1703947 -3.85761990e-01j],
       [ 0.35073051-6.67423340e-01j,  0.32899756-1.65922660e-01j,
         0.36199549+1.70158788e-01j]])

In [ ]:
S_rebuilt / S_rebuilt[0,0]

array([[ 1.        +0.j        , -0.4035494 +0.19687399j,
         0.66022517-1.52130725j],
       [ 0.0492536 +0.88879111j,  0.93941376-0.65476659j,
        -0.34726658-0.78618786j],
       [ 0.71479325-1.36021728j,  0.67050122-0.3381525j ,
         0.73775143+0.34678578j]])

In [ ]:
S_rebuilt.conj().T @ S_rebuilt

array([[ 1.00000000e+00+1.31726415e-17j,  1.10992661e-16+8.72183968e-17j,
         5.98846412e-16+4.94304874e-16j],
       [ 1.10992661e-16-4.84592509e-17j,  5.00000000e-01-3.98285607e-18j,
        -2.04635942e-16-1.64199076e-17j],
       [ 5.98846412e-16-4.88417675e-16j, -2.04635942e-16+1.10988902e-19j,
         1.00000000e+00-1.21122893e-17j]])

In [ ]:
U_rebuilt = photon_unitary(S_rebuilt, photons)

In [ ]:
U

array([[-0.56702093-0.21133125j,  0.43652808+0.38497648j,
        -0.12569491+0.35119156j, -0.12977857-0.24800985j,
         0.16530281-0.19244446j,  0.10873656+0.03732412j],
       [ 0.29986088+0.54784797j,  0.09353256-0.00643833j,
        -0.36989736+0.04116174j, -0.02003941-0.30762489j,
         0.50057331-0.0154208j ,  0.08801303+0.33022043j],
       [ 0.02715681+0.29513886j, -0.29803083+0.33150638j,
         0.48649403+0.25811359j,  0.46367688-0.30511087j,
         0.02007708-0.12224103j,  0.16179897-0.24601601j],
       [ 0.06795328-0.31504803j,  0.09212081-0.31770594j,
         0.51123807+0.25700761j,  0.05852773-0.15934892j,
         0.35712453+0.21193962j, -0.33462803+0.38214746j],
       [ 0.12594016-0.1758571j ,  0.48036677-0.18347193j,
         0.03255072-0.18928854j,  0.4263886 -0.07097713j,
        -0.05838246+0.28031085j,  0.61890883-0.00580026j],
       [ 0.06224593-0.03733467j,  0.27836504+0.04902144j,
         0.03410602-0.23146849j,  0.34685323+0.42726497j,
         

In [ ]:
from qoptcraft.state import Fock