In [1]:
import numpy as np

from qoptcraft.invariant import spectral_invariant
from qoptcraft import Fock

### Same spectral invariant

In [2]:
state = Fock(3, 3)
spectral_invariant(state, subspace="full")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j, 1.-0.14285714j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j])

In [3]:
state= 1/np.sqrt(2)*Fock(6, 0) + 1/np.sqrt(2)*Fock(0, 6)
spectral_invariant(state, subspace="full")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 1.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j, 0.-0.14285714j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j])

### Different invariant

In [26]:
state = Fock(3, 3, 0)
spectral_invariant(state, subspace="image")

array([0.+0.08333333j, 0.+0.08333333j, 0.+0.05952381j, 0.+0.08333333j,
       0.+0.05952381j, 0.+0.03571429j, 0.+0.08333333j, 0.+0.05952381j,
       0.+0.03571429j, 0.+0.01190476j, 0.+0.08333333j, 0.+0.05952381j,
       0.+0.03571429j, 0.+0.01190476j, 0.-0.01190476j, 0.+0.08333333j,
       0.+0.05952381j, 0.+0.03571429j, 0.+0.01190476j, 0.-0.01190476j,
       0.-0.03571429j, 0.+0.08333333j, 0.+0.05952381j, 0.+0.03571429j,
       0.+0.01190476j, 0.-0.01190476j, 0.-0.03571429j, 0.-0.05952381j])

In [27]:
state= Fock(1,1,4)
spectral_invariant(state, subspace="image")

array([0.-0.01190476j, 0.-0.01190476j, 0.+0.01190476j, 0.-0.01190476j,
       0.+0.01190476j, 0.+0.03571429j, 0.-0.01190476j, 0.+0.01190476j,
       0.+0.03571429j, 0.+0.05952381j, 0.-0.01190476j, 0.+0.01190476j,
       0.+0.03571429j, 0.+0.05952381j, 0.+0.08333333j, 0.-0.01190476j,
       0.+0.01190476j, 0.+0.03571429j, 0.+0.05952381j, 0.+0.08333333j,
       0.+0.10714286j, 0.-0.01190476j, 0.+0.01190476j, 0.+0.03571429j,
       0.+0.05952381j, 0.+0.08333333j, 0.+0.10714286j, 0.+0.13095238j])

### Hong-Ou-Mandel

In [6]:
state = Fock(1, 1)
spectral_invariant(state, subspace="full")

array([0.+0.33333333j, 0.+0.33333333j, 0.+0.33333333j, 0.-0.33333333j,
       1.-0.33333333j, 0.-0.33333333j])

In [7]:
state= Fock(2,0)-Fock(0,2)
spectral_invariant(state, subspace="full")

array([0.00000000e+00+0.33333333j, 0.00000000e+00+0.33333333j,
       0.00000000e+00+0.33333333j, 1.00000000e+00-0.33333333j,
       2.43084904e-17-0.33333333j, 0.00000000e+00-0.33333333j])

In [8]:
state = Fock(2, 0)
spectral_invariant(state, subspace="full")

array([0.+0.83333333j, 0.+0.33333333j, 0.-0.16666667j, 1.-0.83333333j,
       0.-0.33333333j, 0.+0.16666667j])

### More examples

In [9]:
state = Fock(4, 4)
spectral_invariant(state, subspace="full")

array([0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j,
       0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j,
       0.+0.11111111j, 0.-0.11111111j, 0.-0.11111111j, 0.-0.11111111j,
       0.-0.11111111j, 1.-0.11111111j, 0.-0.11111111j, 0.-0.11111111j,
       0.-0.11111111j, 0.-0.11111111j])

In [10]:
state= 1/np.sqrt(2)*Fock(8, 0) + 1/np.sqrt(2)*Fock(0, 8)
spectral_invariant(state, subspace="full")

array([0.00000000e+00+0.11111111j, 0.00000000e+00+0.11111111j,
       0.00000000e+00+0.11111111j, 0.00000000e+00+0.11111111j,
       0.00000000e+00+0.11111111j, 0.00000000e+00+0.11111111j,
       0.00000000e+00+0.11111111j, 0.00000000e+00+0.11111111j,
       0.00000000e+00+0.11111111j, 1.00000000e+00-0.11111111j,
       2.02570753e-18-0.11111111j, 0.00000000e+00-0.11111111j,
       0.00000000e+00-0.11111111j, 0.00000000e+00-0.11111111j,
       0.00000000e+00-0.11111111j, 0.00000000e+00-0.11111111j,
       0.00000000e+00-0.11111111j, 0.00000000e+00-0.11111111j])

In [11]:
state = Fock(5, 5)
spectral_invariant(state, subspace="full")

array([0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j,
       0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j,
       0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j, 0.-0.09090909j,
       0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j,
       1.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j,
       0.-0.09090909j, 0.-0.09090909j])

In [12]:
state= 1/np.sqrt(2)*Fock(10, 0) + 1/np.sqrt(2)*Fock(0, 10)
spectral_invariant(state, subspace="full")

array([ 0.00000000e+00+0.09090909j,  0.00000000e+00+0.09090909j,
        0.00000000e+00+0.09090909j,  0.00000000e+00+0.09090909j,
        0.00000000e+00+0.09090909j,  0.00000000e+00+0.09090909j,
        0.00000000e+00+0.09090909j,  0.00000000e+00+0.09090909j,
        0.00000000e+00+0.09090909j,  0.00000000e+00+0.09090909j,
        0.00000000e+00+0.09090909j,  1.00000000e+00-0.09090909j,
       -8.28698536e-19-0.09090909j,  0.00000000e+00-0.09090909j,
        0.00000000e+00-0.09090909j,  0.00000000e+00-0.09090909j,
        0.00000000e+00-0.09090909j,  0.00000000e+00-0.09090909j,
        0.00000000e+00-0.09090909j,  0.00000000e+00-0.09090909j,
        0.00000000e+00-0.09090909j,  0.00000000e+00-0.09090909j])

### NOON

In [13]:
state = Fock(2, 2)
spectral_invariant(state, subspace="image")

array([0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j])

In [14]:
spectral_invariant(state, subspace="full")

array([0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.-0.2j, 0.-0.2j,
       1.-0.2j, 0.-0.2j, 0.-0.2j])

In [15]:
state = Fock(4, 0) + Fock(0, 4)
spectral_invariant(state, subspace="image")

array([0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j])

In [16]:
spectral_invariant(state, subspace="full")

array([0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 1.-0.2j, 0.-0.2j,
       0.-0.2j, 0.-0.2j, 0.-0.2j])

In [17]:
state = Fock(3, 3)
spectral_invariant(state, subspace="image")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j])

In [18]:
spectral_invariant(state, subspace="full")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j, 1.-0.14285714j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j])

In [19]:
state = Fock(6, 0) + Fock(0, 6)
spectral_invariant(state, subspace="image")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j])

In [20]:
spectral_invariant(state, subspace="full")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 1.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j, 0.-0.14285714j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j])