In [13]:
import numpy as np

from qoptcraft.invariant import spectral_invariant
from qoptcraft import Fock

### Same spectral invariant

In [14]:
state = Fock(3, 3)
spectral_invariant(state, subspace="full")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j, 0.+0.85714286j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j])

In [15]:
state= 1/np.sqrt(2)*Fock(6, 0) + 1/np.sqrt(2)*Fock(0, 6)
spectral_invariant(state, subspace="full")

array([ 0.+0.14285714j,  0.+0.14285714j,  0.+0.14285714j,  0.+0.14285714j,
        0.+0.14285714j,  0.+0.14285714j,  0.+0.14285714j,  0.-0.14285714j,
       -0.+0.85714286j,  0.-0.14285714j,  0.-0.14285714j,  0.-0.14285714j,
        0.-0.14285714j,  0.-0.14285714j])

### Different invariant

In [16]:
state = Fock(3, 3, 0)
spectral_invariant(state, subspace="full")

array([0.+0.08333333j, 0.+0.08333333j, 0.+0.05952381j, 0.+0.08333333j,
       0.+0.05952381j, 0.+0.03571429j, 0.+0.08333333j, 0.+0.05952381j,
       0.+0.03571429j, 0.+0.01190476j, 0.+0.08333333j, 0.+0.05952381j,
       0.+0.03571429j, 0.+0.01190476j, 0.-0.01190476j, 0.+0.08333333j,
       0.+0.05952381j, 0.+0.03571429j, 0.+0.01190476j, 0.-0.01190476j,
       0.-0.03571429j, 0.+0.08333333j, 0.+0.05952381j, 0.+0.03571429j,
       0.+0.01190476j, 0.-0.01190476j, 0.-0.03571429j, 0.-0.05952381j,
       0.-0.08333333j, 0.-0.08333333j, 0.-0.05952381j, 0.-0.08333333j,
       0.-0.05952381j, 0.-0.03571429j, 0.+0.91666667j, 0.-0.05952381j,
       0.-0.03571429j, 0.-0.01190476j, 0.-0.08333333j, 0.-0.05952381j,
       0.-0.03571429j, 0.-0.01190476j, 0.+0.01190476j, 0.-0.08333333j,
       0.-0.05952381j, 0.-0.03571429j, 0.-0.01190476j, 0.+0.01190476j,
       0.+0.03571429j, 0.-0.08333333j, 0.-0.05952381j, 0.-0.03571429j,
       0.-0.01190476j, 0.+0.01190476j, 0.+0.03571429j, 0.+0.05952381j])

In [17]:
state= Fock(1,1,4)
spectral_invariant(state, subspace="full")

array([0.-0.01190476j, 0.-0.01190476j, 0.+0.01190476j, 0.-0.01190476j,
       0.+0.01190476j, 0.+0.03571429j, 0.-0.01190476j, 0.+0.01190476j,
       0.+0.03571429j, 0.+0.05952381j, 0.-0.01190476j, 0.+0.01190476j,
       0.+0.03571429j, 0.+0.05952381j, 0.+0.08333333j, 0.-0.01190476j,
       0.+0.01190476j, 0.+0.03571429j, 0.+0.05952381j, 0.+0.08333333j,
       0.+0.10714286j, 0.-0.01190476j, 0.+0.01190476j, 0.+0.03571429j,
       0.+0.05952381j, 0.+0.08333333j, 0.+0.10714286j, 0.+0.13095238j,
       0.+0.01190476j, 0.+0.01190476j, 0.-0.01190476j, 0.+0.01190476j,
       0.-0.01190476j, 0.-0.03571429j, 0.+0.01190476j, 0.-0.01190476j,
       0.-0.03571429j, 0.-0.05952381j, 0.+0.01190476j, 0.-0.01190476j,
       0.-0.03571429j, 0.-0.05952381j, 0.-0.08333333j, 0.+0.01190476j,
       0.-0.01190476j, 0.-0.03571429j, 0.-0.05952381j, 0.+0.91666667j,
       0.-0.10714286j, 0.+0.01190476j, 0.-0.01190476j, 0.-0.03571429j,
       0.-0.05952381j, 0.-0.08333333j, 0.-0.10714286j, 0.-0.13095238j])

### Hong-Ou-Mandel

In [18]:
state = Fock(1, 1)
spectral_invariant(state, subspace="full")

array([0.+0.33333333j, 0.+0.33333333j, 0.+0.33333333j, 0.-0.33333333j,
       0.+0.66666667j, 0.-0.33333333j])

In [19]:
state= Fock(2,0)-Fock(0,2)
spectral_invariant(state, subspace="full")

array([0.+0.33333333j, 0.+0.33333333j, 0.+0.33333333j, 0.+0.66666667j,
       0.-0.33333333j, 0.-0.33333333j])

In [20]:
state = Fock(2, 0)
spectral_invariant(state, subspace="full")

array([0.+0.83333333j, 0.+0.33333333j, 0.-0.16666667j, 0.+0.16666667j,
       0.-0.33333333j, 0.+0.16666667j])

### More examples

In [21]:
state = Fock(4, 4)
spectral_invariant(state, subspace="full")

array([0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j,
       0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j,
       0.+0.11111111j, 0.-0.11111111j, 0.-0.11111111j, 0.-0.11111111j,
       0.-0.11111111j, 0.+0.88888889j, 0.-0.11111111j, 0.-0.11111111j,
       0.-0.11111111j, 0.-0.11111111j])

In [22]:
state= 1/np.sqrt(2)*Fock(8, 0) + 1/np.sqrt(2)*Fock(0, 8)
spectral_invariant(state, subspace="full")

array([0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j,
       0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j, 0.+0.11111111j,
       0.+0.11111111j, 0.+0.88888889j, 0.-0.11111111j, 0.-0.11111111j,
       0.-0.11111111j, 0.-0.11111111j, 0.-0.11111111j, 0.-0.11111111j,
       0.-0.11111111j, 0.-0.11111111j])

In [23]:
state = Fock(5, 5)
spectral_invariant(state, subspace="full")

array([0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j,
       0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j,
       0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j, 0.-0.09090909j,
       0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j,
       0.+0.90909091j, 0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j,
       0.-0.09090909j, 0.-0.09090909j])

In [24]:
state= 1/np.sqrt(2)*Fock(10, 0) + 1/np.sqrt(2)*Fock(0, 10)
spectral_invariant(state, subspace="full")

array([0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j,
       0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j,
       0.+0.09090909j, 0.+0.09090909j, 0.+0.09090909j, 0.+0.90909091j,
       0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j,
       0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j, 0.-0.09090909j,
       0.-0.09090909j, 0.-0.09090909j])

### NOON

In [28]:
state = Fock(2, 2)
spectral_invariant(state, subspace="image")

array([0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j])

In [31]:
spectral_invariant(state, subspace="full")

array([0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.8j, 0.-0.2j,
       0.-0.2j, 0.-0.2j, 0.-0.2j])

In [30]:
state = Fock(4, 0) + Fock(0, 4)
spectral_invariant(state, subspace="image")

array([0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j])

In [32]:
spectral_invariant(state, subspace="full")

array([0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.2j, 0.+0.8j, 0.-0.2j,
       0.-0.2j, 0.-0.2j, 0.-0.2j])

In [33]:
state = Fock(3, 3)
spectral_invariant(state, subspace="image")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j])

In [34]:
spectral_invariant(state, subspace="full")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j, 0.+0.85714286j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j])

In [35]:
state = Fock(6, 0) + Fock(0, 6)
spectral_invariant(state, subspace="image")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j])

In [36]:
spectral_invariant(state, subspace="full")

array([0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j,
       0.+0.14285714j, 0.+0.14285714j, 0.+0.14285714j, 0.-0.14285714j,
       0.+0.85714286j, 0.-0.14285714j, 0.-0.14285714j, 0.-0.14285714j,
       0.-0.14285714j, 0.-0.14285714j])