In [2]:
from math import sqrt
from qoptcraft.state import PureState, Fock

In [3]:
state = Fock(1,0) + Fock(0,1)

In [9]:
state.coefs

array([1, 1])

In [10]:
state.amplitudes

array([0.70710678, 0.70710678])

In [4]:
state.creation(0)

0.82 * (2, 0) + 
0.58 * (1, 1)

In [6]:
state.creation(0).coefs

array([1.41421356, 1.        ])

In [ ]:
state.creation(0).coefs

In [7]:
sum(Fock(0,2,1))

3

In [8]:
len(Fock(2,1))

2

In [12]:
sqrt(2) * Fock(2,0) + Fock(1,1)

0.82 * (2, 0) + 
0.58 * (1, 1)

In [4]:
import numpy as np

a = np.array([[1,1,1], [2,2,2], [3,3,3]])
a.ravel()

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [6]:
a = np.ravel([[1,1,1], [2,2,2], [3,3,3]])

In [7]:
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3])