In [1]:
import qoptcraft

ImportError: cannot import name 'entanglement' from partially initialized module 'qoptcraft' (most likely due to a circular import) (/Users/milvus/miniconda3/envs/test/lib/python3.11/site-packages/qoptcraft/__init__.py)

In [1]:
from math import sqrt
from qoptcraft.state import PureState, Fock

ModuleNotFoundError: No module named 'qoptcraft.state'

In [2]:
state = Fock(1,0) + Fock(0,1)

In [3]:
state.creation(0)

0.58 * (1, 1) + 
0.82 * (2, 0)

In [4]:
sqrt(2) * Fock(2,0) + Fock(1,1)

0.58 * (1, 1) + 
0.82 * (2, 0)

In [5]:
state.creation(0).coefs

array([1.        , 1.41421356])

In [10]:
sum(Fock(0,2,1))

3

In [12]:
len(Fock(2,1))

2

In [20]:
import sympy
import numpy as np

coefs = sympy.MatrixSymbol("coefs", 2, 2)

In [21]:
new_array = coefs @ np.ones((2,2))

In [25]:
coefs[1,:] @ np.ones((2,2))


array([[1.0*coefs[1, 0] + 1.0*coefs[1, 1],
        1.0*coefs[1, 0] + 1.0*coefs[1, 1]]], dtype=object)

In [23]:
new_array

array([[1.0*coefs[0, 0] + 1.0*coefs[0, 1],
        1.0*coefs[0, 0] + 1.0*coefs[0, 1]],
       [1.0*coefs[1, 0] + 1.0*coefs[1, 1],
        1.0*coefs[1, 0] + 1.0*coefs[1, 1]]], dtype=object)

In [29]:
from sympy import Matrix, symbols
from sympy.solvers.solveset import linsolve

In [30]:
mat = Matrix(([1, 1, 1, 1], [1, 1, 2, 3]))
mat

Matrix([
[1, 1, 1, 1],
[1, 1, 2, 3]])

In [31]:
x, y, z = symbols('x, y, z')
linsolve(mat, (x, y, z))

{(-y - 1, y, 2)}