In [1]:
import qoptcraft

In [2]:
from math import sqrt
from qoptcraft.state import PureState, Fock

In [3]:
state = Fock(1,0) + Fock(0,1)

In [4]:
state.creation(0)

0.58 * (1, 1) + 
0.82 * (2, 0)

In [5]:
sqrt(2) * Fock(2,0) + Fock(1,1)

0.58 * (1, 1) + 
0.82 * (2, 0)

In [6]:
state.creation(0).coefs

array([1.        , 1.41421356])

In [7]:
sum(Fock(0,2,1))

3

In [8]:
len(Fock(2,1))

TypeError: object of type 'int' has no len()

In [2]:
from itertools import combinations

import numpy as np
from numpy.typing import NDArray
from numpy.testing import assert_allclose
import pytest

from qoptcraft.operators import haar_random_unitary
from qoptcraft.optical_elements import beam_splitter
from qoptcraft.evolution import photon_unitary


beamsplitter = beam_splitter(np.pi / 4, 0, 2, 0, 1)
hong_ou_mandel = np.array(
    [[0.5, 1 / np.sqrt(2), 0.5], [-1 / np.sqrt(2), 0, 1 / np.sqrt(2)], [0.5, -1 / np.sqrt(2), 0.5]]
)
photonic_matrix = photon_unitary(beamsplitter, 2, "heisenberg")

In [3]:
photonic_matrix

array([[ 0.5       +0.j,  0.70710677+0.j,  0.5       +0.j],
       [-0.70710677+0.j,  0.        +0.j,  0.70710677+0.j],
       [ 0.5       +0.j, -0.70710677+0.j,  0.5       +0.j]],
      dtype=complex64)

In [4]:
hong_ou_mandel

array([[ 0.5       ,  0.70710678,  0.5       ],
       [-0.70710678,  0.        ,  0.70710678],
       [ 0.5       , -0.70710678,  0.5       ]])

In [5]:
assert_allclose(photonic_matrix, hong_ou_mandel, atol=1e-10)